# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  scene_config = debug
endif
ifeq ($(config),release)
  scene_config = release
endif

PROJECTS := scene

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

scene:
ifneq (,$(scene_config))
	@echo "==== Building scene ($(scene_config)) ===="
	@${MAKE} --no-print-directory -C . -f scene.make config=$(scene_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f scene.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   scene"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"